import Navbar from "../navbar"
export default function page() {
  return (
    <div className="w-screen">
        <Navbar/>
        <div className="flex flex-col min-h-screen bg-customRedMedium text-sm px-6 space-y-4 py-6">
            <p className="text-2xl pb-4 tracking-widest">RECHERCHE</p>
            <p className="text-customYellow">Vous recherchez des amis, des parents, cette rubrique vous est ouverte. Adressez nous un message précis et court. Les recherches figurant sur notre ancien site sont conservées dans nos archives. Vous désirez faire figurer à nouveau votre annonce, merci de l'actualiser.</p>
            <div className="text-customRed border-b border-t border-white font-bold text-lg tracking-widest">mars 2009</div>
            <div className="text-customYellow flex flex-col space-y-4 text-justify">
                <p>:R01/0309 : Je souhaite reprendre contact avec :</p>
                <p>1: <span className="text-white">Viviane et Nimet Jabès.</span>  Elles ont dû changer de nom quand elles se sont mariées si cela a été le cas.  Elles sont les filles du poète Edmond Jabès qui était un des meilleurs amis  de mon père.  Avec Viviane, nous allions au même cours de danse, chez Sonia Ivanova, au Caire et avec Nimet j'ai eu des vacances en Autriche et en Italie avec Lilian de Botton. Mariane Cicurel faisait aussi partie du voyage et c'était entre 1952 et 1955. </p>
                <p>2: <span className="text-white">Jacqueline Garboua</span> dont je sais qu'elle a épousé un Monsieur Barbier et que j'ai perdue de vue lorsque j'ai quitté la région parisienne en 1966-67. <br/>Victoria Truffert <span className="text-customRed">victoriatruffert@orange.fr </span></p> 
                <p>R02/0309 : Je recherche des informations concernant mon grand père <span className="text-white">Isaac Cohen dit Zaki</span> né à Tantah (Egypte) en 1891 et qui a vécu à Paris entre 1910 et 1914 avant de rentrer en Egypte où il a épousé Inès Botton en 1920. Merci d'avance de m'aider à reconstituer son parcours. <br/>Danièle Casanova (née Cohen) <span className="text-customRed">danicasa@numericable.fr</span> </p> 
                <p> R03/0309 : Je recherche des photos du <span className="text-white"></span>"Trou du Diable" qui se trouvait à Alexandrie. <br/>Moïse Rahmani <span className="text-customRed">morah_1@hotmail.com</span> </p>
            </div>

            <div className="text-customRed border-b border-t border-white font-bold text-lg tracking-widest">décembre 2008</div>
            <div className="text-customYellow flex flex-col space-y-4 text-justify">
                <p>R01/1208 : Je recherche un vieux copain du lycee francais de bab-el-louk parti en Angleterre au nom de <span className="text-white">Leon Hakim</span>. Son pere avait un magasin a la rue Soliman Pacha si quelqu’un le connait ou bien se rappelle de lui sera me ferais bien plaisir. <br/>Mireille Gibert</p>
                <p>R02/1208 : Un vieux copain qui a émigré en Israel au nom de <span className="text-white">Avraham Borreda</span>, était dans votre liste de recherche avec le e-mail sous le nom de <span className="text-customRed hover:text-customYellow">borreda@neision.n.il</span> mais l’adresse n’etait pas correcte. Veuillez si vous avez certaines information me les communiquer. Je reside en Australie. <br/>Mireille Gibert <span className="text-customRed hover:text-customYellow">mireilg@bigpond.net.au</span></p>
                <p>R03/1208 : Je suis partie d&apos;Egypte en février 1956. J&apos;étais élève au Lycée français du Caire de 1951 à 1956. Je ne retrouve plus aucune photo ni souvenir de l&apos;époque et cela m&apos;a fait chaud au cœur de découvrir votre site. Merci à celles et ceux qui en ont eu l’initiative. <br/>Je n’ai retrouvé qu’une photo de la classe de 7ème  où figure M. <span className="text-white">Gazalé</span>, qui a été mon professeur, mais je ne figure pas sur la photo et ne suis pas certaine de reconnaître des camarades de classe car suppose que je devais être dans une classe parallèle. Sauf erreur l’année était 1953. <br/>Quelqu’un possède-t-il des photos de la classe de 4ème avec <span className="text-white">Mme Gamila Badr</span> en tant que professeur de Mathématiques 1955 ou 1956? Ce fut ma dernière année d’école au Lycée.Je ne pense malheureusement pas pouvoir vous apporter beaucoup de souvenir mais si j&apos;en retrouve, je prendrai contact avec vous. Meilleures salutations,<br/> Denise Volet (ex Sarkis).</p> 
                <p>R04/1208 : Je suis la fille unique d'Yvette (nee Moche) Levi and de Leon Levy, decede.  Nous avons quitter l'Egypte en 1956. En cherchant une recette, nous avons retrouver votre addresse il y a quelques semaines and nous sommes si heureuses d'avoir fait votre connaissance!  D'ailleurs, nous vous demandons si vous avez un groupe AJOE en Amerique.  Mes parent aussi ont vecu a Paris pendent plusieurs annees et etaient amis avec Nina et Zaki Abravanelle, Alice Crespin et plusieurs d'autres.J'aimerai tellement que Maman soit en contacte avec ces gens mais je ne sais pas comment!  Est-ce-vous pouvez m'aider? Merci pour nous avoir donner de si bons souvenirs! Excusez mon francais, nous sommes en Amerique depuis 1958! <br/>Joyce (nee Levy) MintzerJ. <span className="text-customRed hover:text-customYellow">jmintzer4a@verizon.net</span></p> 
                <p>R05/1208 : Je suis un égyptien établi en France depuis pas mal d'année, et je porte en moi directement ou indirectement des souvenirs de nos amis d'antan ave qui des égyptiens ont partagé le quotidien. Mon père était très lié à M. Elie Politi depuis son arrivée en Egypte au siècle dernier. Malheureusement je n'ai pas de souvenir direct de M. Politi mais je me rappelle des cadeaux qu'il me faisait parvenir quand j'étais enfant ,c'était des jouets que j'avais longtemps gardé. J'ai entrepris d'écrire un livre sur le règne du Roi Farouk et bien sûr dans lequel j'évoque le souvenir de mon père et de son ami M. Elie Politi que Dieu les ait en miséricorde, et je souhaite lui rendre l'hommage qui lui est dû . M. Politi avait un fils dont je ne connais pas le prénom il doit être un peu plus âgé que moi c'est à dire un sexagénaire avancé, si par hasard il est membre de votre association, je vous prie de lui transmettre mes amitiés en souvenir de nos parents respectifs. Amicalement.<br/>Nabil GOHARY</p>
            </div>

            <div className="text-customRed border-b border-t border-white font-bold text-lg tracking-widest">septembre 2008</div>
            <div className="text-customYellow flex flex-col space-y-4 text-justify">
                <p>R01/0908 : My name is <span className="text-white">Nisso Moadeb</span>, I am looking for  friends name Charles Barough And Albert Gohar, we were at lycee francais du bab-al-look from 1957 to 1960. <br/>please contact me <span className="text-customRed hover:text-customYellow">fbs.factory1@ aol.com</span> </p>
                <p>R02/0908 : Bonjour, pour des raisons généalogiques je cherche des informations sur une société de charité fondée à Port Said en 1917 par une certaine <span className="text-white">Madame VITA</span> dont j'ignore absolument tout. Voyez-vous de quoi il peut s'agir ? <br/>Thomas Baruchel.</p>
                <p>R03/0908 : Je vous prie de bien vouloir m'informer comment je pourrai retrouver une vielle copine, nom de célibataire <span className="text-white">Bela Bercovitch</span>. Merci d'avance. <br/>Richard Hantower <span className="text-customRed hover:text-customYellow">rihantower@uol.com.br</span></p> 
                <p>R04/0809 : Est-ce que quelqu'un pourrait me donner des precisions sur la maison de retraite [appelee en ce temps-la''asile des vieillards''] de <span className="text-white">Helouann</span>? ou d''un hotel? de sejour de longue duree. Comme beaucoup je tente d''ecrire mes souvenirs a l'intention de mes enfants et petits-enfants.. Merci d''avance.<br/> Lorys ex-Beressi <span className="text-customRed hover:text-customYellow">bittyl@bezeqint.net</span></p> 
                <p>R05/0809 : Bonjour a tous. Je suis la fille ainee d'<span className="text-white">Adrienne Ascher-Leon</span>. Je demeure au Canada. Ma mere jusqu'a ses derniers moments ne me parlait que de l'Egypte ou elle a passe sa jeunesse ,a fait partie du groupe jeunesse puis a epouse mon pere Martin Nissim Leon ,puis sont arrives les enfants ,Alain (decede) Michelle et David. Nous avons quittes en 1949 je n'avais que 4 ans, j'ai ete au Lycee Francais en maternelle MAMAN a garder dans une boite toutes les photos relatant une grande partie de sa vie en EGYPTE, LE CAIRE, ALEXANDRIE, HELIOPOLIS. Ses amies etaient les Hagag, Pinto, Doueg et tant d'autres dont les noms m'echapent a present.Au Caire nous avons habite rue Soliman Pacha le roof garden au dessus du journal du Caire. D'apres les souvenirs de MAMAN notre vie etait assez comfortable, nous avons quitte precipitament du au fait que mon pere etait Juif Allemand, nous avons embarques dans un navire le HARTZA rester dans ce navire jusqu'a la naissance de l'etat d'ISRAEL. Nous avons vecus de 1949 a 1954 en ISRAEL puis regagnes la FRANCE ou j'ai grandi. Nous avons quitte la FRANCE en 1969 pour le CANADA ou nous vivons actuellement. Je voudrai pouvoir communiquer avec des personnes qui ont connu Ma Mere qui nous a quitte en Novembre 2007. Cette lettre manque de precision et de details ,mais je souhaite pouvoir en son Nom ouvrir un nouveau chapitre. Je vous remercie d'avance. <br/>Michelle Leon <span className="text-customRed hover:text-customYellow">michette.l @videotron.ca </span></p>
            </div>

        
        </div>
    </div>
  )
}