export const Sidebar = [
    {title: 'ACTUALITE', url: '/' },
    {title: 'NOTRE HISTOIRE', url: '/history'},
    {title: 'CULTURE', url: '/culture'},
    {title: "LA GALERIE", url: '/gallery'},
    {title: "ALBUM PHOTOS", url: '/album'},
    {title: "CUISINE", url: '/cuisine'},
    {title: "RECHERCHES", url: '/research'},
    {title: "TEMOIGNAGES", url: '/testimonies'},
    {title: "SORTIE D'EGYPTE", url: '/exit'},
    {title: "ADHESION", url: '/form'},
    {title: "CONTACT", url: '/'}
];

export const description = [
    "Chers amis de l'AJOE,",
    "Ces deux dernières années ont été comme pour tout le monde une période très difficile pour notre association et a vu disparaître beaucoup de nos très chers amis.",
    "C'est ainsi que David HARARI s'en est allé en plein confinement le 7 avril 2020.",
    "L'AJOE perd encore une fois un membre très actif, bien plus qu'un trésorier, un très grand ami et nous lui rendons hommage. Il nous manque terriblement.",
    "Mais, pour toute une nouvelle génération qui arrive, notre histoire se doit d'être transmise. C'est pourquoi nous avons décidé de programmer et de produire pour une soirée exceptionnelle, le 15 décembre prochain spectacle d'Isabelle de Botton",
    "'La Parisienne d'Alexandrie' qui retrace avec tant de justesse, tendresse et humour l'épopée des Juifs d'Egypte.",
]

export const gallery = [
    {name: 'Piera Rossie', image: '/potrait/piera_r.jpg'},
    {name: 'Denise Zayan', image: '/potrait/denise_z.jpg'},
    {name: 'Viviane Douek', image: '/potrait/viviane_d.jpeg'},
    {name: 'Henri Cohen', image: '/potrait/henri_c.jpeg'},
    {name: 'Camille Fox', image: '/potrait/camille_f.jpg'},
    {name: 'Gaby Fossier-Zein', image: ''},
    {name: 'Viviane Israel', image: '/potrait/viviane_i.jpeg'},
    {name: 'Dora Ovadia', image: '/potrait/dora_o.jpg'}
]

export const history = [
    `En ce mois de février 2008, le bâtiment impressionnant des grands magasins Omar Effendi au coin des rues Abdel-Aziz et Rouchdi est presque vide, attendant sa restauration sous l'égide des nouveaux propriétaires Saoudiens, la société commerciale Anwal. La succursale de la rue Adli a déjà subi un lifting, et d'après l'hebdomadaire El-Ahram du 5 Février 2008, la chaîne Omar Effendi, après des années de déclin, retrouverait ses beaux jours.Effectivement, une certaine nostalgie pour les grands magasins d'antan, se fait déjà sentir parmi l’élite résidentielle étrangère au Caire. Avant l'exode des années soixante, la plupart de ces grands magasins appartenaient à des familles Juives: Cicurel (d’Izmir), Chemla (de Tunis), Gategno, Hannaux, Adès, Benzion etc., exception faite pour les Magasins Sednaoui et Davies Bryan, qui appartenaient à des Chrétiens Syriens et des Gallois.`,
    `L'histoire de Omar Effendi, autrefois mieux connu sous le nom Ets. Orosdi-Back, commence en 1855, avec la fondation d'une  maison de vêtements prêts-à-porter à Istanbul, par Adolf Orosdi (antérieurement Adolf Schnabel, la traduction en hongrois du mot 'bec'). Avant cela, il était officier au service de Kossuth, le champion de liberté Hongrois déchu, et avait trouvé refuge dans l'Empire Ottoman. La famille Orosdi fit à deux reprises des mariages avec la famille Back commerciale, également juive et d'origine austro-hongroise. Un quartet de Léon et Philippe Orosdi avec Hermann et Joseph Back, établirent graduellement une chaîne de succursales à Bucarest, Plovdiv, Salonique, Izmir, Adana, Samsun, Alep, Beyrouth, Bagdad, Basra, Tunis, Bizerte, et pour des épisodes  brèves à Tabriz, Téhéran, et plus tard à Casablanca et Mekhnès. Depuis 1888, leur siège social était à Paris, d'ou ils dirigeaient des agences d’achat dans plusieurs villes industrielles européennes (un enjeu  que nous trouvons aussi chez les magasins Chemla) et aussi au Japon. A Paris, Hermann Back “de Surany” et Léon Orosdi, se convertirent au catholicisme et marièrent leurs filles dans la haute bourgeoisie française.`,
    `En Egypte, c'était non seulement le Caire et Alexandrie, mais aussi Port-Saïd, et des succursales furent établies pendant un certain temps à Tanta et Zaqaziq. Le directeur local Philippe Back, contribua  à la construction de la synagogue Chaar Hachamayim de la rue Adli, qui a dernièrement célèbré son centenaire. Avant de s'établir en Hongrie pour une carrière politique, il avait également patronné des excavations importantes en Egypte.`,
    `Les aspirations du Khédive Ismail de construire un “Paris sur le Nil” se reflétaient dans la visibilité resplendissante des grand magasins, construits dans le style architectural Parisien. La coupole du bâtiment Tiring (un des premiers magasins austro-hongrois) sur la Place d’Ataba, et la 'cathédrale de consommation'  Sednaoui à la Place Khazindar toute proche, sont autant de pierres précieuses posées sur la couronne Cairote à cette époque. Orosdi-Back, qui faisait surtout du commerce en gros, se développait progressivement vers le commerce en détail. En 1909, il  ouvrit son établissement au quartier du Mouski,  en y introduisant - comme dans d'autres grands magasins - la pratique des prix fixes et les stocks étalés avec accès libre. Il offrait à sa clientèle des 'Nouveautés' et des 'Articles de Paris', des produits de 'confection'  européenne pour la marche, pour les hommes, pour les enfants et les femmes, des vêtements prêts-à-porter, alors encore très chers, des chapeaux pour femmes et des tarbouches pour hommes qui deviennent des articles de premier rang.`,
    `En fait, en 1899 Orosdi-Back devient la force mouvante pour la formation du Syndicat des confectionneurs de tarbouches à Strakonitz (Tcheque), qui approvisionnait la majorité du marché ottoman, l'Egypte inclus. Orosdi-Back étaient aussi forts en bonneterie (les bas, les chaussettes, les sous-vêtements), manufactures de technique tricot avancé.`,
    `Plus tard, vinrent s'ajouter les bottes, les chaussures, les cannes et les parasols (assemblés en partie dans une usine à Istanbul). De même la quincaillerie, articles de ménage, articles de voyage et ameublement, de faux bijoux modernes qui vinrent briser les conventions traditionnelles des bijoux en or, des instruments de musique européens et des gramophones. En 1908, Orodi-Back produisit les disques du fameux chanteur égyptien Yusuf al-Minyalawi. Pendant la première décennie du 20e siècle, Orosdi-Back possédait également une usine de montres  à  La  Chaud  de Fond  en  Suisse.`,
    `Plus   tard,   vinrent   s'ajouter   les  bottes,  les chaussures, les cannes et les parasols (assemblés en partie dans une usine à Istanbul). De même la quincaillerie, articles de ménage, articles de voyage et ameublement, de faux bijoux modernes qui vinrent briser les conventions traditionnelles des bijoux en or, des instruments de musique européens et des gramophones.`,
    `Le personnel dans les grands magasins était en général plus élevé en nombre que celui dans l'industrie naissante (quelques centaines par entreprise). Plusieurs chefs de rayon et employés supérieurs étaient des hommes, tandis que les clients étaient servis par des vendeuses (cet aspect ne gagna jamais le statut littéraire de Au Bonheur des Dames de Zola, mais il surgit occasionnellement au cinéma égyptien). Une bonne partie des employés étaient des juifs et “de bonne famille”. Les vendeuses se devaient de parler quatre à cinq langues: l’arabe, l’anglais, l’italien, parfois le grec et toujours le français.”`,
]

export const history2 = [
    `Un certain déclin se fait déjà sentir pendant les années trente. Les succursales à Tanta et à Zaqaziq sont forcées de fermer. Avec le nationalisme économique croissant, surgissent de temps en temps des boycottages de marchandises européennes, et les grands magasins authentiquement égyptiens font leur apparence.`,
    `La Révolution nassérienne enfin évinça l’élite étrangère résidentielle, neutralisa sa propre bourgeoisie indigène, séquestra et nationalisa les grands magasins. En réduisant sévèrement l’importation de marchandises, le régime des Officiers Libres croyait jouer ainsi un rôle économique, pour le profit des grands magasins nationalisés.`,
    `Les Egyptiens - dans une démonstration de force juste avant l'accord final d’août 1958 - acquirent Orosdi-Back. Dorénavant, les magasins adoptèrent exclusivement le nom d’Omar Effendi. Ironiquement, c’était un retour à un ancien titre ottoman effendi, qui avait été aboli par la Révolution. Mais, à l'insu des égyptiens c'est aussi le nom antérieur du magasin qui avait été construit au quartier Eminönü à Istanbul aux environs de 1907, et qui existe toujours au même emplacement.`,
    `La nationalisation conduisit les grands magasins vers une médiocrité grise, vendant des marchandises de basse qualité. Des plaintes s'élevèrent contre les prix exagérés et les grands stocks restés invendus. Mais en dépit de la nationalisation, les affaires se développèrent; Omar Effendi détient aujourd'hui 82 magasins. Les années soixante-dix, années de l’Infitah et d'une certaine libéralisation des importations,  mêlaient une fois de plus les cartes. Avec la mondialisation,  des shopping malls furent construits au Caire (récemment, un mall Carrefour à Ma'adi, copie du Carrefour français).`,
    `A partir de 1996, le gouvernement égyptien s'est embarqué dans un programme de privatisation de certaines sociétés, qui furent nationalisées dans le passé. La vente d'Omar Effendi fut la première transaction d'un long processus. Un grand débat eut lieu, non seulement sur le principe même de la privatisation, mais aussi sur le prix de 'l'ancienne diva' qu'était Orosdi-Back. Ironiquement, des critiques nationalistes trouvaient le prix trop bas (pour un bien que le gouvernement avait lui-même obtenu pour un prix également trop bas). L'acheteur saoudien, Anwal United Trading Co., acquit en 2006 la chaîne Omar Effendi, pour le prix de LE 589.5m. (a peu près NIS 390 m.). La chaîne représente de grandes marques de mode françaises et internationales de consommation luxueuse, comme Etam, OshKosh, Kookai, Jacadi et Bottega Verde. Les nouveaux propriétaires espèrent évidemment vendre ces produits de luxe en Egypte aussi, et - sans le dire explicitement "sur les bases d'un succès d'origine juive" -  de ramener Omar Effendi à sa belle notoriété d'antan.`
]
export const history3 = `Du même auteur:  "Who Needed Department Stores in Egypt? From Orosdi-Back to Omar Effendi", Middle Eastern Studies, vol. 43/2 (2007), pp. 175-192 ; et European Department Stores and Middle Eastern Consumers, the Orosdi-Back Saga ( Istanbul: Ottoman Bank and Archives and Research Centre 2007)`

export const cuisine = [
    `Humidifier les galettes et les envelopper dans un torchon sec. Couper en petits morceaux le poulet ou le séfrito`,
    `Badigeonner le plat avec un peu d'huile. Battre les oeufs en ajoutant le jus de cuisson de la viande ou du poulet et rallonger si besoin avec du bouillon, rectifier l'assaisonnement en ajoutant sel et poivre. Passer y rapidement les galettes une à une et les poser dans le plat. Bien tapisser le fond et le tour. Pour le fond on peut mettre 3 épaisseurs de galettes. Ajouter la viande ou le poulet et recouvrir de galettes.`,
    `Arroser avec le reste du jus de cuisson et mettre à dorer sur la plaque de cuisson. Retourner la mayna afin qu'elle cuise sur l'autre face. Finir à four température douce afin qu'elle reste tendre.`,
]

export const exit = [
    {name: 'Parents Frenkel', image: '/exit/f_route1.jpg'},
    {name: 'Grand Père Bezalel Frenkel', image: '/exit/f_route2.jpg'},
    {name: 'Tante Adassa', image: '/exit/f_route3.jpg'},
    {name: 'Oncle David', image: '/exit/f_route4.jpg'},
    {name: 'Oncle Harry', image: '/exit/f_route5.jpg'},
]

export const album = ['/album/Img-1.jpeg', '/album/Img-2.jpeg', '/album/Img-3.jpeg', '/album/Img-4.jpeg', '/album/Img-5.jpeg', '/album/Img-6.jpeg', '/album/Img-7.jpeg', '/album/Img-8.jpeg',]

export const actualite = [
    `On dit que " la mémoire est propre à tous, [mais] l'histoire est interprétée". En ce sens, la mémoire appartient individuellement aux personnes, ou collectivement aux familles et aux communautés, mais l'histoire est recherchée, découverte, et souvent redécouverte, par des savants qui ne vivent pas nécessairement dans la période, ou dans le milieu de l'objet qu'ils étudient. En bref, elle est conditionnée par des recherches, et ensuite reconstruite.`,
    `Quand il s'agit de l'histoire des juifs en Égypte – je voudrais même dire – de leur apogée au dix-neuvième siècle et durant la première moitié du vingtième siècle, l'historien est confronté non seulement à quelques défis : leur dispersion après les années 1960 ; le manque, l'inaccessibilité ou la disparition des archives pertinentes ; des périodiques souvent épars et incomplets, mais aussi à des souvenirs idéalisés ou partiaux et également à la nostalgie d’une époque disparue. Comme étudiant du Moyen-Orient, qui n’était en rien connecté à l'Égypte, je me suis essayé parfois à la reconstitution de certains aspects de cette histoire des juifs en Égypte : l'histoire de la SG des Sucreries, une entreprise initialement juive – contenue dans la biographie de son directeur Henri Naus Bey, catholique belge, que j'ai appelée récupérée ; l'histoire de la société de Wadi Kom Ombo, la plus grande société de mise en valeur de terres agricoles, dont les actionnaires étaient juifs dans l'ensemble, que j'ai appelée fouillée; et la "saga", comme je l'ai dit, des Orosdi-Backs, deux familles juives hongroises entremariées qui ont fondé une chaîne de grands magasins partout au Moyen-Orient, dont les quelque quatre-vingt succursales Omar Effendi en Égypte survivent encore. Par ailleurs, pour ceux qui ont lu mon travail antérieur, - après avoir été privatisée et vendue aux Saoudiens en 2006, le Printemps arabe a eu pour conséquence de retourner l'entreprise aux mains des égyptiens.`,
    `Pour cette occasion festive de l'inauguration d'une nouvelle chaire universitaire, j'ai choisi de parler d'une personnalité juive, dans le contexte de son temps, c’est-à-dire la première moitié du vingtième siècle. Depuis le déménagement de sa famille d'Istanbul au Caire et à Alexandrie ; à ses accomplissements professionnels, et jusqu’à son départ tragique et son décès à Nice. C'est plus qu'une simple biographie, parce qu'elle englobe la sphère publique, et peut donc être pertinente pour la compréhension d'une société au sens large, et de l'ensemble d'une époque.`,
    `L'homme duquel je vais vous parler est - je suppose - connu de certains d'entre vous comme « Oncle Isaac », un des héros d’André Aciman dans son livre Out of Egypt, un livre de souvenirs publiéen 1994 et depuistraduit en plusieurs langues. En françaisil porte le titre Adieu Alexandrie et en hébreu Layla Aharon beAlexandria. André Aciman est professeur distingué de la théorie littéraire à CUNY (son nom devrait être prononcé acιman en Turc (dj), mais asiman est devenu l’usage depuis longtemps).`,
    `En effet, Adieu Alexandrie est l'un des plus plaisants mémoires rédigés par les anciens juifs d'Egypte au cours des dernières années, même si l'histoire d'une famille entière, contrainte de quitter l'Egypte, est certainement une tragédie. Il est profondément imbibé de ce qui était, je crois, l'atmosphère qui régnait en Egypte à la fin des années 1950.`,
    `La littérature des réminiscences des juifs d'Egypte a augmenté de manière impressionnante ces dernières décennies, et elle est devenue un genre littéraire en soi, variant entre romantisme nostalgique et autobiographie méticuleuse. Étant donné que l'historiographie a pris récemment une tournure dite "littéraire", les souvenirs personnels et collectifs ont acquis une valeur reconnue.`,
    `Le livre d’Aciman, toutefois, a provoqué une dispute en 1996. Mon bon ami - je pense que je dirai même notre bon ami-, Samir Raafat, qui a écrit avec sensibilité et même avec admiration sur les juifs d’Égypte, dans le Journal égyptien, le Courrier égyptien, et plus tard sur son site internet, a accusé Aciman de plagiat et de distorsion. Le litige portait sur l'identité de la figure dominante du livre, l'oncle Vili, - présumé être un espion britannique, mais se présentant comme un protagoniste fasciste. En fin de compte, il s'est avéré que l'oncle était en réalité Maurice George Levi et qu'il s'est installé en Angleterre. Samir Raafat a été particulièrement outré car Aciman avait reçu un prix de $ 30 000 pour une œuvre de non-fiction. Écriture, qui, aurait dû, selon lui, comporter des notes méticuleuses, mais qui manquent dans ce livre. Je n'avais jamais lu ce livre pour ma part comme une histoire dans la veine positiviste, mais comme une sorte de récit familial, où vérité et imagination souvent s'entremêlent, c'est à dire entre fiction et non-fiction.`,
    `Depuis plusieurs années, je m’en étais tenu à cela, j'avais considéré les caractères de l’oncle Vili et de l’oncle Isaac comme réels mais toutefois littéraires, des héros un peu romancés, flottants entre le tragique et l'amusant. Il est pertinent de mentionner ici que dans cette famille alexandrine, plutôt que cairote, l'oncle Isaac, s'impose comme "le plus occidentalisé de la famille", érudit, ayant de nombreuses relations, un peu arrogant et parfois cynique.`,
    `Sans l’existence de l’internet, je n’aurais probablement jamais découvert que l'oncle Isaac était nul autre que le Isaac Levi, l'homme que j'avais rencontré dans mon étude antérieure sur Henri Naus, l'industriel belge. Naus crée en 1922 la Fédération des Industries, et bientôt Levi en devint le secrétaire-général.`,
    `C’est ainsi que j'ai découvert un autre livre de souvenirs l’intéressant, une autobiographie plus factuelle, celle de feu Frédéric Galimidi, qui m'a fait découvrir l'identité réelle de l’oncle Isaac. Le livre de Galimidi, Alexandrie sur la Seine (un jeu de mots sur "Paris sur le Nil » du Khédive Isma'il) décrit son oncle Isaac. Il décrit avec admiration, l'homme qui l'a mis sur la voie de la carrière d'avocat, que poursuivent aujourd'hui son fils et sa fille à Paris. C'est l'occasion pour moi de remercier sa famille pour la convivialité et l’hospitalité dont ils ont fait preuve à mon égard récemment à Paris.`,
    `Ici nous arrivons à un point d'inversion entre mémoire et histoire. L'oncle Isaac n'est pas une personne moins réelle qu’Isaac Levi. Je ne voudrais pas impliquer par cela l’existence d’un Dr. Jekyll et d’un Mr. Hyde, dans le sens négatif et positif, ou deux personnalités totalement différentes, mais la question se pose de savoir comment nous pouvons arriver de l'oncle amusant d’Aciman , et de l'oncle un peu pédant de Galimidi, - en fait la même personne-, à l'envergure publique du Dr Isaac Levi et à son vrai rôle dans la société égyptienne. Attendons de voir ce qu'un historien pourrait savoir sur lui.`,
]

export const actualite2 = [
    {
        title:'Histoire', 
        data: [
            `Isacco Giuseppe Levi est né à Istanbul en 1878, dans l'ancienne communauté juive italienne. Son père était un fournisseur d'étoffes à l'armée ottomane. Il est le second enfant parmi neuf frères et sœurs. Après avoir été scolarisé dans des écoles italiennes, il se rend à Naples afin de poursuivre des études supérieures, où il obtient un doctorat en droit de la vénérable Université Frederico Secundo et un autre diplôme en langues orientales à l'aussi prestigieuse Université Orientale, avec le grec comme sujet majeur. En 1903, il arrive en Egypte, où ses parents et frères et sœurs s'installeront plus tard, la plupart d'entre eux à Alexandrie. Comme nous savons, à l'époque, les conditions en Egypte jouaient le rôle d’un aimant sur nombre de ceux qui aspiraient à de nouvelles opportunités économiques, ou surtout à plus de liberté. Initialement, Isaac Levi travaille en tant qu'avocat au Tribunaux mixtes, puis au Consulat italien, et bientôt il entre au Service des Statistiques.`,
            `Je prétends que la connexion italienne était sans doute aussi importante que le fait qu’il fut juif ; Cela transparait dans sa biographie. La rencontre d’Isaac Levi avec le Prince Fouad doit avoir été un atout: nous nous souvenons que le futur Sultan et Roi avait passé une partie de son enfance à Naples et par la suite a également suivi un entraînement militaire à Turin. Quoi qu'il en soit, André Aciman représente les parents d'Isaac, en 1956, comme se moquant de ses relations avec l'ex-roi et son entourage. Relations si cruellement en défaut au moment critique quand à son tour le Roi Farouk n'est d'aucune aide non plus. Remarquant sur un comportement déplorable de ce dernier, déjà à un jeune âge, Levi est cité par Galimidi disant: " Fouad, lui était un Roi!".`,
            `Considérons maintenant la carrière du Dr Isaac Levi sous quatre rubriques :`,
        ]
    },
    {
        title:'(1) Statistiques',
        data: [
            `En 1905 Levi est entré au département de statistiques (alors encore partie du Ministère des Finances), démissionnant finalement comme Directeur Général en 1923. Roger Owen à Harvard et Timothy Mitchell à la Columbia University, ont analysé récemment ce qu'on appelle aujourd'hui la "production de statistiques" et la séquence des " régimes statistiques" en Egypte. Chaque régime avait ses propres instruments et objectifs (initialement limités à la démographie, l'éducation, a santé publique, la dette publique etc..). Selon Owen, une troisième phase a commencé en 1905, lorsque Lord Cromer rétablit le service statistique en mettant l'accent sur les intérêts coloniaux, - la propriété foncière, le coton et le commerce. Je ne suis pas sûr, cependant, qu’avec Isaac Levi, il ne soit pas advenu une quatrième étape, comme requis par l'émergent état national égyptien.`,
            `Là aussi apparaît une connexion italienne. Après Colucci Bey et Frederico Amici Bey ses prédécesseurs étrangers au 19ème siècle, un autre italien, Giuseppe Randone, qui avait dirigé le recensement de 1882, intervint en 1905 comme nouveau directeur. Il a recruté Levi. Nous ne savons pas si la branche des statistiques avait fait partie des études juridiques de Isaac Levi – comme l'économie politique- mais cela aurait bien pu être le cas. En effet, peu de temps avant, Alberto Errera, juriste de formation, avait enseigné la statistique à Naples. A cette époque, les italiens étaient éminents dans le domaine, de Luigi Bodio à Corrado Gini (du coefficient éponyme) - quelles que soient leurs orientations politiques divergentes.`,
            `Randone a entrepris une politique de professionnalisation de la fonction, bientôt renforcée par Levi qui lui a succédé comme "l'animateur vif", selon les mots du savant français François Ireton. Cela ressort également d’un compte rendu publié par Isaac Levi en 1925, après sa démission. La production de statistiques a progressivement embrassé de plus en plus de branches du gouvernement et ajouté de nouveaux domaines. Et en incluant des graphiques également. L'Annuaire Statistique (de 1909) est paru en 1910 et a bénéficié d’une appréciation immédiate, également de l'étranger. Les statistiques sont maintenant devenues nationales, et également publiques, et disponibles non seulement en français mais aussi en arabe.`,
            `Certes, des statistiques fiables ont toujours revêtu une signification pour tout gouvernement. Galimidi rapporte que, lors d’une révolte des bédouins qui avait soudainement éclatée, le Roi consulta Levi, qui a été en mesure de lui fournir une estimation réaliste des tribus impliquées, - évidemment pour pouvoir mettre fin à cette révolte. Interrogé pour savoir quelle récompense il souhaitait recevoir, Levi, prétendument, répondit simplement au Roi : Salamtak, ya galalat al-Malik! Votre bien-être, Majesté !`,
            `Par ailleurs, Levi a obtenu de multiples honneurs au cours de sa vie; il fut membre honoraire d’organisations professionnelles internationales et reçut des décorations étrangères. Pourtant, il n'est jamais devenu bey ou pacha- peut-être ne disposant pas des ressources appropriées - et est toujours resté le docteur Levi.`,
        ]
    },
    {
        title:`(2) La Société d'Economie Politique, de Législation et de Statistique`,
        data: [
            `En 1909, Isaac Levi était devenu co-fondateur de la Société d'Economie Politique, de Législation et de Statistique, - à mon avis, la plus importante d'un certain nombre de ces sociétés savantes. Elle se mit à explorer les problèmes de la " vie nationale". L'économie politique signifiant ce que nous appelons aujourd'hui simplement l'économie. Au fil du temps, le préfixe de l'association a évolué de khédiviale , sultanique et royale et est enfin devenu égyptienne. Le Prince Fouad, le futur roi, était personnellement impliqué. Plus tard, l'association occupa un imposant édifice de la rue Ramsès d'aujourd'hui qui porte encore le nom en français ! Avec quelques 200 membres au début et 600 dans les années 1940, avocats, banquiers, entrepreneurs, hauts fonctionnaires, etc., elle organisait des débats et conférences hebdomadaires. En bref, elle fut un lieu de rencontres pour l'intelligentsia égyptienne et l'élite des résidents étrangers. La majorité de cette dernière catégorie considérait l'Egypte comme sa soi-disant "patrie adoptée". Ça ne veut pas dire la participation de beaucoup de Juifs, et pourtant nous y trouvons les noms d'Adda, Aghion, Cattaui, Cohen, Green, Jabes, Morporgo, Mortera, Mosseri, Nahmias, Najar et Perez, - pour la plupart, des avocats issus de ces familles. Dès sa création, Isaac Levi servit, bien en vue, comme secrétaire de la société.`,
            `L'association entreprit la publication de la revue l'Egypte Contemporaine (alors encore en français). Tous les trois aspects, l'économie, la législation, et les statistiques y sont amplement couverts, raison pourquoi laquelle aujourd'hui, elle peut encore être considérée comme une source éminente pour l'étude concernant le discours socio-économique de la période prérévolutionnaire. Cependant, il fallait éviter les querelles des partis politiques ou autres sujets sensibles qui étaient interdits; inutile de chercher mention des frères musulmans de cette époque, par exemple.`,
            `L'association mérite plus d'attention que je ne peux lui consacrer ici.
            Faute d'un parlement, initialement- ou d’une représentation vraiment populaire et efficace plus tard, on pourrait considérer cette société savante comme le reflet des aspirations contemporaines de toute la population. Les historiographes plus récents l’ignorent car ils la considèrent comme une institution colonialiste ou réactionnaire, étroitement alliée avec le roi, ou avec des politiciens hautement controversés comme Isma'il Sidqi. Et une institution noyautée d'étrangers. Toutefois, il serait utile de systématiquement comparer les conférences et les articles aux lois adoptées durant la période de la monarchie (comme Malak Badrāwi l’a récemment fait spécifiquement pourles discussions budgétaires au parlementmais en ignorant l’Egypte Contemporaine).`,
            `Ceci s'applique également pour la quarantaine d’articles érudits que Dr. Isaac Levi a publié au cours des années dans l'Egypte Contemporaine et dans quelques autres revues. Presque tous en français, quelques-uns en Italien, mais je n’en ai jamais trouvé un écrit en arabe. C'est dans ces articles, je suggère, que sa contribution principale doit être recherchée. On trouve des tableaux statistiques des prix du coton, de commerce extérieur, du mouvement maritime, des taux de change, qui sont régulièrement placés dans le journal. Mais, en outre, pour la première fois il y avait aussi un débat sérieux sur la statistique des revenus nationaux, et leur signification. En fait, des analyses scientifiques.`,
            `Son premier grand article traite des écarts arbitraires des prix des denrées sur les différents marchés de nourriture du Caire et entre les villes et villages, statistiques dont il est allé recueillir des données sur place, ce qui est tout à fait remarquable. Il a écrit ce premier article avec Germain Martin, un historien de l'économie français qui avait été professeur invité à la nouvelle université égyptienne (et plus tard ministre, il faut le mentionner, sous Vichy). Leur recommandation était de publier des mercuriales sur les prix courants. En plus, Levi était un des pionniers d'une discussion systématique sur le revenu national de l'Égypte, c'est-à-dire son PNB, qu'il a estimé sensiblement plus élevé, plus optimiste,`,
            `que ne l’avaient fait les britanniques apparemment afin de montrer que le pays n'était pas encore mûr pour l'indépendance. On se souvient, ce fut peu de temps après 1922, la date de la première « fausse » indépendance. La planification et l'efficacité économique sont toujours proches de son cœur, il plaide constamment pour l'industrialisation et pour un tarif douanier protecteur (qui est entré en effet en 1930). On trouve également des articles sur la nécessité d'encourager le tourisme, la formation commerciale, et aussi les coopératives de consommateurs. En bref, des nouveaux domaines du discours sur l'économie nationale, qu'il faut encore examiner de plus près afin de déterminer leur impact (possible) sur le long terme.`,
            `Pendant une courte période (1919-1921), Isaac Levi a enseigné l'économie politique à l'Ecole de Droit, en ce temps encore "sultanique". En 1922, par ailleurs, il a servi comme membre du Conseil Supérieur Economique (un corps mixte, l'établissement dont il avait lui-même proposé la création). On peut ajouter qu'en 1938, il allait devenir un membre de la commission qui étudie la réforme fiscale, suivant l'abolition formelle des Capitulations à Montreux.`,
        ]
    },
    {
        title:`(3) la Fédération des Industries`, 
        data: [
            `En 1925, âgé 47 ans, le Dr Isaac Levi, quitte le Service de statistiques pour un nouveau poste. Il devient Secrétaire Général de l'Association`,
            `(par la suite Fédération) des Industries égyptiennes, qui avait été`,
            `fondée en1922 par l'industriel Belge Henri Naus Bey, avec quelques autres entrepreneurs étrangers installés en Egypte. Il restera à ce poste pendant vingt-huit ans. La Fédération avait été au départ une organisation d’étrangers – principalement des industriels installés dans le pays (avec quelques égyptiens), mais dans les deux dizaines d'années qui suivirent, elle est devenue le principal organisme des chefs d'entreprises autochtones Ici aussi, Levi contribue à mettre en place un journal appelé l'Egypte Industrielle. Malheureusement, la plupart des articles publiés dans cette revue (éditoriaux et articles informatifs) ne sont pas signés, donc nous pouvons seulement supposer que Levi lui-même a contribué plus que quelques-uns d'entre eux.`,
            `La Fédération des Industries n'a pas été décrite avec bonté par les historiens, que ce soient des Egyptiens, ou des universitaires occidentaux. Jacques Berque, Marius Deeb, Joel Beinin et Zachary Lockman, tous l’ont considérée comme un instrument contre les grèves des salariés, contre les revendications des ouvriers, contre la législation en leur faveur (par exemple, la Loi de lutte contre l'analphabétisme, qui imposa aux employeurs d’en assumer les coûts et à laquelle ils s’opposèrent). L'Egypte Industriellea même montré des tendances pro-Mussolini, - quoique uniquement durant les années vingt, mais pas plus tard pour autant que j’ai pu le vérifier. J'ai tendance à accepter certaines de leurs critiques, même si la Fédération n'a jamais été assez puissante pour vraiment contrecarrer le progrès. On doit l’admettre, une Fédération des Industries n'aurait pas agi autrement en tant que syndicat patronal. Mais ici je préfère suivre l'approche plus tolérante de Robert Tignor de Princeton. Dès la fin des années 1920, la Fédération a vu ses membres augmenter et, rapidement il y avait une majorité égyptienne indigène. Peu d'entre eux étaient des Juifs, mais nous savons que Levi lui-même, par exemple, exerçait la fonction d'administrateur dans plusieurs petites entreprises industrielles dont je sais très peu, par exemple les Textiles Kahira, les Minoteries et Silex, et Egyptian Neons. Mon argument principal: la Fédération a certainement travaillé pour la promotion de l'industrialisation. Levi a également joué un rôle important dans l'organisation de certaines des grandes expositions agricoles et industrielles dans le Caire de l'époque.`,
        ]
    },
    {
        title:`(4) Activités juives`, 
        data: [
            `Nous ne savons pas grand-chose de ses activités dans d'autres sociétés publiques et organisations, dont plusieurs étaient dans la sphère italienne mentionnée par notre collègue Marta Petricioli. Ici, cependant, nous proposons de revenir à la partie juive de sa biographie. Bien que moins prononcée qu'en ce qui concerne sa carrière publique, l'Annuaire des Juifs d' Egypte qui est apparu plusieurs fois dans le début des années 1940, mentionne néanmoins son nom en tant que membre de plusieurs organismes juifs de bienfaisance , par exemple la Société de Bienfaisance Israélite du Caire, l'Œuvre de la Goutte de Lait, l'Œuvre d'Apprentissage Salomon Cicurel, ainsi que les Amis du Collège Rabbinique de Rhodes – qui aurait été une institution pro-Mussolini -et les Amis de l'Université Hébraïque. A propos, à cet égard, il y a quelques années j'ai eu accès aux dossiers de cette dernière et j'ai découvert ses contributions financières considérables. En Alexandrie, cette association était dirigée par Vera Nadler, qui n’était autre que la future belle-mère de Boutros Boutros-Ghali.`,
            `Galimidi est d'avis que Levi, et le Grand Rabbin Haïm Nahum Effendi, ont contribué à exempter les Juifs des restrictions en temps de guerre adoptées contre les ressortissants italiens et allemands. Mais, plus important encore, Isaac Levi a également siégé au Conseil de la communauté juive du Caire. C'est pourquoi, lorsqu'en novembre 1946, sa présidence change des main de René Cattaui à Salvator Cicurel – une transition vue par Gudrun , Krämer dans son livre bien connu, comme un signe de la démocratisation et permettant ainsi plus de latitude pour les éléments de la classe moyenne supérieure, Isaac Levi en devient le vice-président.`,
        ]
    },
    {
        title:`La fin`, 
        data: [
            `Bientôt après la révolution de 1952, où il était déjà près de la retraite de la Fédération des Industries, Isaac Levi a été évincé de son poste de Secrétaire Général. En plus, l'assassinat de l'un des nouveaux cadres par un serviteur qui avait été fidèle à Levi, a jeté un discrédit sur lui. Pourtant, dans les années 1950, il est mentionné encore avec tous ses titres dans cet annuaire annuel des élites, le Mondain Egyptien et du Proche Orient. Toutefois, à ce moment-là, il était déjà établi en toute sécurité à Nice. Après tout, à un moment donné, il avait obtenu la nationalité française, même si l'historien Anthony Gorman le considère comme une " mutamassir" quintessenciel, ce qui signifie égyptianisé. Et voilà, contre l'avis des parents et des amis, il semble, il se sentait assez en sécurité pour retourner en Égypte afin d'y régler ses affaires. Ici, les versions de Aciman et Galimidi se chevauchent et divergent en partie, mais le fait est, qu'il a été arrêté et interrogé sévèrement pour des accusations fabriquées. Et néanmoins enfin libéré. Tragiquement, il retourne à Nice en 1961, un homme brisé, en fauteuil roulant, et mourut quelques mois plus tard.`,
            `Étonnamment, ou pas si étonnamment peut-être, je n’ai pu trouver jusqu'ici qu'un seul avis de décès dans les médias égyptiens, - par un entomologiste italien Anastase Alfieri, et publié en 1963 dans le Bulletin de l'Institut Egypte. Pas un mot dans l'Egypte Contemporaine ou dans l'Egypte Industrielle, qui avaient été ses "propres" revues.`,
        ]
    },
    {
        title:`En conclusion:`, 
        data: [
            `Il y a plus que seulement des souvenirs. Le point saillant est que toutes les institutions dont j'ai parlé continuent d'exister, mais sans les juifs qui y avaient joué un rôle actif. En somme: Une grande partie de la routine du service statistique (après Levi dirigé par l'anglais James Craig, qui a été assassiné le Samedi Noir de 1952), a été transférée à CAPMAS de l'ère Nassérienne. La Société égyptienne d'économie politique occupe toujours son majestueux édifice, et même si elle a perdu son ancien rôle, elle organise toujours des réunions occasionnelles. L'Egypte Contemporaine,maintenant appelée Misr al-Mu'asira, apparaît entièrement en arabe (avec un résumé en anglais). La Fédération des Industries, Ittihad al-Sina'at al-Misriyya, autrefois située dans la tour de Immobilia, a déménagé dans un bâtiment moderne; elle n'est peut-être plus ce qu'elle était, mais elle est néanmoins vivante. Le trimestriel Misr al-Sina'iyya parait encore. D'ailleurs, son livre du jubilé d'or de 1972, comme tant de comptes-rendus commémoratifs en Egypte, résume l'ère avant 1952 en deux maigres pages, ignorant Naus et Levi. Il s'agit d'un problème d'écriture de l'histoire en Égypte.`,
            `Souvenirs et recherches historiques, les deux, ont leur signification. Ils doivent agir ensemble, notamment les souvenirs – qu’ils soient écrits, imprimés, photographiés, ou transmis oralement –, et être intégrés avec les sources historiographiques actuelles, des tendances et des idées. Ce n'est pas facile, parce que l'Egypte est après tout l'Égypte, et les Juifs sont des Juifs. Mais c’est là je pense, que se profile le défi pour le Professeur Tamar Zewi, nouveau titulaire de la Chaire Barda et ses étudiants: non seulement pour raconter l'héritage, mais pour comprendre son contexte et sa signification.`,
        ]
    },
]

export const actualiteImage = [
    {title:`portrait de Isaac Levy`, image: `/actualite/isaac.jpg`},
    {title:`couverture livre Aciman`, image: `/actualite/couv_livre_aciman.jpg`},
    {title:`couverture"L'Egypte contemporaine"`, image: `/actualite/couv_livre_egypte.jpg`},
    {title:`siège de laSociété Savante`, image: `/actualite/siege_societe.jpg`},
]